"""create tabels

Revision ID: 96fe21aa6523
Revises: 
Create Date: 2017-01-07 11:02:58.521262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96fe21aa6523'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('record',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('line_no', sa.Integer(), nullable=True),
    sa.Column('record_type', sa.String(length=100), nullable=True),
    sa.Column('record_date', sa.Date(), nullable=True),
    sa.Column('record_time', sa.Time(), nullable=True),
    sa.Column('record_command', sa.String(length=100), nullable=True),
    sa.Column('record_fullname', sa.String(length=200), nullable=True),
    sa.Column('record_additional_information', sa.Text(), nullable=True),
    sa.Column('record_string', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_index('command_index', 'record', ['record_command'], unique=False)
    op.create_index('date_time_index', 'record', ['repo_id', 'version_id', 'line_no', 'record_date', 'record_time'], unique=False)
    op.create_index('fullname_index', 'record', ['record_fullname'], unique=False)
    op.create_index('record_line_no_index', 'record', ['repo_id', 'version_id', 'line_no'], unique=True)
    op.create_index('record_type', 'record', ['record_type'], unique=False)
    op.create_table('record.nwp_pos.nwpc_sp',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('line_no', sa.Integer(), nullable=True),
    sa.Column('record_type', sa.String(length=100), nullable=True),
    sa.Column('record_date', sa.Date(), nullable=True),
    sa.Column('record_time', sa.Time(), nullable=True),
    sa.Column('record_command', sa.String(length=100), nullable=True),
    sa.Column('record_fullname', sa.String(length=200), nullable=True),
    sa.Column('record_additional_information', sa.Text(), nullable=True),
    sa.Column('record_string', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_index('command_index', 'record.nwp_pos.nwpc_sp', ['record_command'], unique=False)
    op.create_index('date_time_index', 'record.nwp_pos.nwpc_sp', ['repo_id', 'version_id', 'line_no', 'record_date', 'record_time'], unique=False)
    op.create_index('fullname_index', 'record.nwp_pos.nwpc_sp', ['record_fullname'], unique=False)
    op.create_index('record_line_no_index', 'record.nwp_pos.nwpc_sp', ['repo_id', 'version_id', 'line_no'], unique=True)
    op.create_index('record_type', 'record.nwp_pos.nwpc_sp', ['record_type'], unique=False)
    op.create_table('record.nwp_vfy.nwpc_vfy',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('line_no', sa.Integer(), nullable=True),
    sa.Column('record_type', sa.String(length=100), nullable=True),
    sa.Column('record_date', sa.Date(), nullable=True),
    sa.Column('record_time', sa.Time(), nullable=True),
    sa.Column('record_command', sa.String(length=100), nullable=True),
    sa.Column('record_fullname', sa.String(length=200), nullable=True),
    sa.Column('record_additional_information', sa.Text(), nullable=True),
    sa.Column('record_string', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_index('command_index', 'record.nwp_vfy.nwpc_vfy', ['record_command'], unique=False)
    op.create_index('date_time_index', 'record.nwp_vfy.nwpc_vfy', ['repo_id', 'version_id', 'line_no', 'record_date', 'record_time'], unique=False)
    op.create_index('fullname_index', 'record.nwp_vfy.nwpc_vfy', ['record_fullname'], unique=False)
    op.create_index('record_line_no_index', 'record.nwp_vfy.nwpc_vfy', ['repo_id', 'version_id', 'line_no'], unique=True)
    op.create_index('record_type', 'record.nwp_vfy.nwpc_vfy', ['record_type'], unique=False)
    op.create_table('record.nwp_xp.eps_nwpc_qu',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('line_no', sa.Integer(), nullable=True),
    sa.Column('record_type', sa.String(length=100), nullable=True),
    sa.Column('record_date', sa.Date(), nullable=True),
    sa.Column('record_time', sa.Time(), nullable=True),
    sa.Column('record_command', sa.String(length=100), nullable=True),
    sa.Column('record_fullname', sa.String(length=200), nullable=True),
    sa.Column('record_additional_information', sa.Text(), nullable=True),
    sa.Column('record_string', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_index('command_index', 'record.nwp_xp.eps_nwpc_qu', ['record_command'], unique=False)
    op.create_index('date_time_index', 'record.nwp_xp.eps_nwpc_qu', ['repo_id', 'version_id', 'line_no', 'record_date', 'record_time'], unique=False)
    op.create_index('fullname_index', 'record.nwp_xp.eps_nwpc_qu', ['record_fullname'], unique=False)
    op.create_index('record_line_no_index', 'record.nwp_xp.eps_nwpc_qu', ['repo_id', 'version_id', 'line_no'], unique=True)
    op.create_index('record_type', 'record.nwp_xp.eps_nwpc_qu', ['record_type'], unique=False)
    op.create_table('record.nwp_xp.nwpc_op',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('line_no', sa.Integer(), nullable=True),
    sa.Column('record_type', sa.String(length=100), nullable=True),
    sa.Column('record_date', sa.Date(), nullable=True),
    sa.Column('record_time', sa.Time(), nullable=True),
    sa.Column('record_command', sa.String(length=100), nullable=True),
    sa.Column('record_fullname', sa.String(length=200), nullable=True),
    sa.Column('record_additional_information', sa.Text(), nullable=True),
    sa.Column('record_string', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_index('command_index', 'record.nwp_xp.nwpc_op', ['record_command'], unique=False)
    op.create_index('date_time_index', 'record.nwp_xp.nwpc_op', ['repo_id', 'version_id', 'line_no', 'record_date', 'record_time'], unique=False)
    op.create_index('fullname_index', 'record.nwp_xp.nwpc_op', ['record_fullname'], unique=False)
    op.create_index('record_line_no_index', 'record.nwp_xp.nwpc_op', ['repo_id', 'version_id', 'line_no'], unique=True)
    op.create_index('record_type', 'record.nwp_xp.nwpc_op', ['record_type'], unique=False)
    op.create_table('record.nwp_xp.nwpc_pd',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('line_no', sa.Integer(), nullable=True),
    sa.Column('record_type', sa.String(length=100), nullable=True),
    sa.Column('record_date', sa.Date(), nullable=True),
    sa.Column('record_time', sa.Time(), nullable=True),
    sa.Column('record_command', sa.String(length=100), nullable=True),
    sa.Column('record_fullname', sa.String(length=200), nullable=True),
    sa.Column('record_additional_information', sa.Text(), nullable=True),
    sa.Column('record_string', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_index('command_index', 'record.nwp_xp.nwpc_pd', ['record_command'], unique=False)
    op.create_index('date_time_index', 'record.nwp_xp.nwpc_pd', ['repo_id', 'version_id', 'line_no', 'record_date', 'record_time'], unique=False)
    op.create_index('fullname_index', 'record.nwp_xp.nwpc_pd', ['record_fullname'], unique=False)
    op.create_index('record_line_no_index', 'record.nwp_xp.nwpc_pd', ['repo_id', 'version_id', 'line_no'], unique=True)
    op.create_index('record_type', 'record.nwp_xp.nwpc_pd', ['record_type'], unique=False)
    op.create_table('record.nwp_xp.nwpc_qu',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('line_no', sa.Integer(), nullable=True),
    sa.Column('record_type', sa.String(length=100), nullable=True),
    sa.Column('record_date', sa.Date(), nullable=True),
    sa.Column('record_time', sa.Time(), nullable=True),
    sa.Column('record_command', sa.String(length=100), nullable=True),
    sa.Column('record_fullname', sa.String(length=200), nullable=True),
    sa.Column('record_additional_information', sa.Text(), nullable=True),
    sa.Column('record_string', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_index('command_index', 'record.nwp_xp.nwpc_qu', ['record_command'], unique=False)
    op.create_index('date_time_index', 'record.nwp_xp.nwpc_qu', ['repo_id', 'version_id', 'line_no', 'record_date', 'record_time'], unique=False)
    op.create_index('fullname_index', 'record.nwp_xp.nwpc_qu', ['record_fullname'], unique=False)
    op.create_index('record_line_no_index', 'record.nwp_xp.nwpc_qu', ['repo_id', 'version_id', 'line_no'], unique=True)
    op.create_index('record_type', 'record.nwp_xp.nwpc_qu', ['record_type'], unique=False)
    op.create_table('repo',
    sa.Column('repo_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('repo_name', sa.String(length=45), nullable=True),
    sa.Column('repo_type', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('repo_id')
    )
    op.create_index('user_repo', 'repo', ['user_id', 'repo_name'], unique=True)
    op.create_table('repo_version',
    sa.Column('repo_version_id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('version_name', sa.String(length=100), nullable=True),
    sa.Column('version_location', sa.String(length=200), nullable=True),
    sa.Column('head_line', sa.Text(), nullable=True),
    sa.Column('collector_id', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('repo_version_id')
    )
    op.create_index('repo_version_index', 'repo_version', ['repo_id', 'version_id'], unique=True)
    op.create_table('sms_repo',
    sa.Column('sms_repo_id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('repo_name', sa.String(length=45), nullable=True),
    sa.Column('repo_location', sa.String(length=100), nullable=True),
    sa.Column('current_version_id', sa.Integer(), nullable=True),
    sa.Column('repo_description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('sms_repo_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('sms_repo')
    op.drop_index('repo_version_index', table_name='repo_version')
    op.drop_table('repo_version')
    op.drop_index('user_repo', table_name='repo')
    op.drop_table('repo')
    op.drop_index('record_type', table_name='record.nwp_xp.nwpc_qu')
    op.drop_index('record_line_no_index', table_name='record.nwp_xp.nwpc_qu')
    op.drop_index('fullname_index', table_name='record.nwp_xp.nwpc_qu')
    op.drop_index('date_time_index', table_name='record.nwp_xp.nwpc_qu')
    op.drop_index('command_index', table_name='record.nwp_xp.nwpc_qu')
    op.drop_table('record.nwp_xp.nwpc_qu')
    op.drop_index('record_type', table_name='record.nwp_xp.nwpc_pd')
    op.drop_index('record_line_no_index', table_name='record.nwp_xp.nwpc_pd')
    op.drop_index('fullname_index', table_name='record.nwp_xp.nwpc_pd')
    op.drop_index('date_time_index', table_name='record.nwp_xp.nwpc_pd')
    op.drop_index('command_index', table_name='record.nwp_xp.nwpc_pd')
    op.drop_table('record.nwp_xp.nwpc_pd')
    op.drop_index('record_type', table_name='record.nwp_xp.nwpc_op')
    op.drop_index('record_line_no_index', table_name='record.nwp_xp.nwpc_op')
    op.drop_index('fullname_index', table_name='record.nwp_xp.nwpc_op')
    op.drop_index('date_time_index', table_name='record.nwp_xp.nwpc_op')
    op.drop_index('command_index', table_name='record.nwp_xp.nwpc_op')
    op.drop_table('record.nwp_xp.nwpc_op')
    op.drop_index('record_type', table_name='record.nwp_xp.eps_nwpc_qu')
    op.drop_index('record_line_no_index', table_name='record.nwp_xp.eps_nwpc_qu')
    op.drop_index('fullname_index', table_name='record.nwp_xp.eps_nwpc_qu')
    op.drop_index('date_time_index', table_name='record.nwp_xp.eps_nwpc_qu')
    op.drop_index('command_index', table_name='record.nwp_xp.eps_nwpc_qu')
    op.drop_table('record.nwp_xp.eps_nwpc_qu')
    op.drop_index('record_type', table_name='record.nwp_vfy.nwpc_vfy')
    op.drop_index('record_line_no_index', table_name='record.nwp_vfy.nwpc_vfy')
    op.drop_index('fullname_index', table_name='record.nwp_vfy.nwpc_vfy')
    op.drop_index('date_time_index', table_name='record.nwp_vfy.nwpc_vfy')
    op.drop_index('command_index', table_name='record.nwp_vfy.nwpc_vfy')
    op.drop_table('record.nwp_vfy.nwpc_vfy')
    op.drop_index('record_type', table_name='record.nwp_pos.nwpc_sp')
    op.drop_index('record_line_no_index', table_name='record.nwp_pos.nwpc_sp')
    op.drop_index('fullname_index', table_name='record.nwp_pos.nwpc_sp')
    op.drop_index('date_time_index', table_name='record.nwp_pos.nwpc_sp')
    op.drop_index('command_index', table_name='record.nwp_pos.nwpc_sp')
    op.drop_table('record.nwp_pos.nwpc_sp')
    op.drop_index('record_type', table_name='record')
    op.drop_index('record_line_no_index', table_name='record')
    op.drop_index('fullname_index', table_name='record')
    op.drop_index('date_time_index', table_name='record')
    op.drop_index('command_index', table_name='record')
    op.drop_table('record')
    # ### end Alembic commands ###
